# Generated by Django 5.0.4 on 2024-04-23 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='course id')),
                ('course_name', models.CharField(max_length=200, verbose_name='course name')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='subject id')),
                ('subject_name', models.CharField(max_length=200, verbose_name='subject name')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acadamic.courses')),
            ],
        ),
    ]
