# Generated by Django 5.0.4 on 2024-04-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notices_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
