# Generated by Django 5.0.4 on 2024-04-23 17:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_leave',
            fields=[
                ('leave_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='student leave id')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='from')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='to')),
                ('name', models.CharField(max_length=30, verbose_name='student name')),
                ('reason', models.CharField(max_length=10000, verbose_name='reason')),
                ('status_accepted', models.BooleanField(default=False, verbose_name='accept')),
                ('status_waiting', models.BooleanField(default=True, verbose_name='mark as read')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_profile.student')),
            ],
        ),
    ]
