# Generated by Django 5.0.4 on 2024-04-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_leave',
            name='status_accepted',
        ),
        migrations.RemoveField(
            model_name='student_leave',
            name='status_waiting',
        ),
        migrations.AddField(
            model_name='student_leave',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('D', 'Declined'), ('W', 'Not Seen')], default='W', help_text='choose', max_length=20, verbose_name='status'),
        ),
    ]
