# Generated by Django 5.0.4 on 2024-04-24 06:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_profile', '0001_initial'),
        ('acadamic', '0002_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 11, 46, 15, 338904), verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acadamic.courses'),
        ),
    ]
